### ISSUE TITLE
Building site doesn't work: _site folder is empty

### ISSUE THREAD

**Issue by ge0ffrey** [awestruct/awestruct.github.io#27] opened 2013-03-11 11:00 UTC
When I build awestruct.org, the _site directory remains empty and nothing is visible on:
  http://localhost:4242
nor
  http://localhost:4242/index.html

This makes it hard to provide a pull request with documentation improvements :)

{code}
$ awestruct -d
Using profile: development
Generating site: http://localhost:4242
Downloaded awestruct-0.4.6
Successfully installed awestruct-0.4.6
1 gem installed
Installing ri documentation for awestruct-0.4.6...
Installing RDoc documentation for awestruct-0.4.6...
ruby: No such file or directory -- yardoc (LoadError)

No such file or directory - gems/gems/awestruct-0.4.6/doc
/usr/lib/ruby/1.9.1/fileutils.rb:1515:in `stat'
/usr/lib/ruby/1.9.1/fileutils.rb:1515:in`block in fu_each_src_dest'
/usr/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
/usr/lib/ruby/1.9.1/fileutils.rb:1513:in`fu_each_src_dest'
/usr/lib/ruby/1.9.1/fileutils.rb:436:in `cp_r'
/home/gdesmet/projects/jboss/awestruct/awestruct.org/_ext/yard.rb:29:in`block in execute'
/home/gdesmet/projects/jboss/awestruct/awestruct.org/_ext/yard.rb:14:in `chdir'
/home/gdesmet/projects/jboss/awestruct/awestruct.org/_ext/yard.rb:14:in`execute'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/pipeline.rb:37:in `block in execute_extensions'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/pipeline.rb:36:in`each'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/pipeline.rb:36:in `execute_extensions'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/pipeline.rb:32:in`execute'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/engine.rb:186:in `execute_pipeline'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/engine.rb:55:in`run'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/cli/generate.rb:19:in `run'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/cli/invoker.rb:97:in`invoke_generate'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/lib/awestruct/cli/invoker.rb:41:in `invoke!'
/var/lib/gems/1.9.1/gems/awestruct-0.4.8/bin/awestruct:9:in`<top (required)>'
/usr/local/bin/awestruct:19:in `load'
/usr/local/bin/awestruct:19:in`<main>'

> > Thin web server (v1.4.1 codename Chromeo)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:4242, CTRL+C to stop
> > {code}

**Comment by zbynek** [comment] 2023-04-13 07:55
> bootstrap isn't installed

Most likely the cause, closing.

**Closed by zbynek** 2023-04-13 07:55 UTC
